find mail/firstrh.com.br/giovanni.cerqueira/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/felipe.pena/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/tatiana.maia/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/curriculorsd/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/nicoly.silva/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/larissa.carvalhosa/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/imayara.santos/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/larissa.cid/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/daiana.carreira/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/marcio.vercoza/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/anna.ribeiro/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/redirect/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/imayara.almeida/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/cristiane.andrade/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/cristiane.domingues/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/atendimento.merck/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/recepcaorsd/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/patricia.torrez/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/recepcao.resende/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/ana.oliveira/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/izabelle.cunha/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/luana.magalhaes/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/elaine.silva/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/joseane.mescolin/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/luana.costa/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/adriana.hoffmann/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/natalia.silva/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/lucas.fonseca/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/bruna.andrade/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/davi.santos/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/faturamento/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/erika.almeida/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/luiz.sa/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/vinicius.torrez/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/beneficios/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/danielle.oliveira/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/adriana.hoffman/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/angela.vanni/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/sabrina.diniz/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/cristiane.martins/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/renan.silva/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/rh/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/tesouraria/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/caroline.oliveira/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/mariapaula.silva/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/danielle.dantas/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/amanda.medeiros/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/patricia.almeida/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/sonia.luiz/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/geisa.rage/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/comercial/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/comercial.resende/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/jacqueline.belmont/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/firstrh/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/operacional/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/atendimento.gsk/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/consultoria/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/vanessa.esperanca/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/curriculo.resende/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/redes.sociais/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/financeiro/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/andrea.hoffman/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/contato/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/portal.corporativo/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/admissao/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/catherine.melo/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/tassia.souza/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/comercial.resende2/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/juridico/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/selecao/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/grupo.financeiro/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/daniel.lima/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/informatica/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/emaildelete/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/meiriane.gomes/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/silvia.pessoa/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/valdiney.alves/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/amanda.porto/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/rita.bento/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/camila.gomes/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/fabiana.nascimento/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/suellen.agrella/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/isabelle.morais/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/maria.montanher/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/cristina.alves/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/webmaster/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/dp/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/vanessa.cabral/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/gabriel.fabiano/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/marcia.zamite/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/michel.aveline/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/rh.resende/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/priscila.lanconi/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/privacidade/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/daniella.santos/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/compliance/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/manutencao/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/qualidade/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/admin/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/administrador/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/adriana.ferreira/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/audit/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/davi.leyendecker/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/debora.silva/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/haisa.gaspar/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/isabele.borba/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/leaderetalent/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/leaderrh/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/no-reply/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/paula.damasceno/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/portal.funcionario/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/rachel.1/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/rm/cur -mtime +20 -type f -ls -delete
find mail/firstrh.com.br/site/cur -mtime +20 -type f -ls -delete