"use strict";

var fotos = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16];
fotos = shuffle(fotos);
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(1) > div:nth-of-type(1)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[0] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(1) > div:nth-of-type(2)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[1] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(1) > div:nth-of-type(3)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[2] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(1) > div:nth-of-type(4)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[3] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(1) > div:nth-of-type(5)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[4] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(1) > div:nth-of-type(6)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[5] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(1) > div:nth-of-type(7)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[6] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(1) > div:nth-of-type(8)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[7] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(2) > div:nth-of-type(1)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[8] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(2) > div:nth-of-type(2)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[9] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(2) > div:nth-of-type(3)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[10] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(2) > div:nth-of-type(4)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[11] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(2) > div:nth-of-type(5)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[12] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(2) > div:nth-of-type(6)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[13] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(2) > div:nth-of-type(7)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[14] + ".png')";
document.querySelector('div.oportunidadesCarrosel > div:nth-of-type(2) > div:nth-of-type(8)').style.backgroundImage = "url('/img_aws/oportunidades/opo_" + fotos[15] + ".png')";